services:
  postgres:
    image: postgres:16-alpine
    container_name: pictionary_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pictionary_user
      POSTGRES_PASSWORD: pictionary_password
      POSTGRES_DB: pictionary_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pictionary_user -d pictionary_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
